name: Build and Publish Docker image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug Secrets
        run: echo "DOCKER_HUB_USERNAME is ${{ secrets.DOCKER_HUB_USERNAME }}"

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Create .env file
        run: echo "${{ secrets.ENV }}"

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/nest-api-test:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nest-api-test:latest

      - name: Update image metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/nest-api-test:latest
          tags: |
            type=sha
          labels: |
            org.opencontainers.image.title=NestJS Example
            org.opencontainers.image.description=Example NestJS application
            org.opencontainers.image.url=https://github.com/${{github.repository}}
            org.opencontainers.image.revision=${{github.sha}}
            org.opencontainers.image.licenses=MIT
